server:
  port: 8083
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
    max-http-post-size: 102400000
#  servlet:
#    context-path: /yqgl
#    session:
#      timeout: 6000s
spring:
  datasource:
    name: template-dev
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      # driver-class-name: oracle.jdbc.driver.OracleDriver
      # url: jdbc:oracle:thin:@192.168.81.17:1521/IMPAXRIS
      # username: ris
      # password: agfa123
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/template?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置。
  mapper-locations: classpath*:/mybatis/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  global-config:
    #刷新mapper 该配置不建议在生产环境打开
    refresh: true
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存,默认为 true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file: ./template.log
  level:
    root: info
#    com:
#      ecdata:
#        yqgl:
#          dao: debug

